### ISSUE TITLE
Add an advertisement/donate button to csharptotypescript.azurewebsites.net

### ISSUE THREAD

**Issue by c0dybrown** [AdrianWilczynski/CSharpToTypeScript#2]
Hey just wanted to let you know that my team and I use your website consistently and I recommend adding an ad or donate button

Thanks for the great free tool, you have really made our lives a lot easier!

**Comment by AdrianWilczynski** [comment]
Thanks. Glad you like it.

It's just a pet project. I don't think it's really popular enough to make setting up ads/donations worth the hassle. I host it on a free Azure tier so It doesn't cost me anything anyway.
