### ISSUE TITLE
Uri not converted correctly

### ISSUE THREAD

**Issue by modesto** [AdrianWilczynski/CSharpToTypeScript#6]
C#

`public Uri Url { get; set; }`

converts to

`url: Uri;`

but should converts to 

`url: string;`

I have dared to do a pull request but I am not sure I have done everything right.

**Comment by modesto** [comment]
Hi! 

I'm using CSharpToTypeScript as a global tool. Can you publish to Nuget the new version?

**Comment by AdrianWilczynski** [comment]
It's published. Sorry for the delay.
